baseURL = 'https://turningoftables.github.io/'
languageCode = 'en-us'
title = 'Turning of Tables'
theme = 'blank'
summaryLength = '40'
paginate = '999999999999999'
[Params]
  description = "Miscellaneous thoughts on software development and testing"
[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Go Quick Reference'
    pageRef = '/goref'
    weight = 20