baseURL = 'https://turningoftables.github.io/'
languageCode = 'en-us'
title = 'Turning of Tables'
theme = 'blank'
summaryLength = '40'
[Params]
  description = "Miscellaneous software development and testing"